
parameters:
- name: configs
  type: object
  default: 
    ASPNETCORE_ENVIRONMENT: Production
    smartthings__PAT: $(PAT)
    sql: $(sql)
    web_insights: $(web_insights)
    worker_insights: $(worker_insights)
    global__dataPath: "/home/ubuntu/data"
    backup__key: $(backup_key)
    backup__baseUrl: $(backup_baseUrl)
    clientUrl: "http://192.168.1.9"

steps:
- ${{ each config in parameters.configs }}:
  - script: 'echo "Environment=${{ config.key }}=''${{ config.value }}''" >> $(Pipeline.Workspace)/drop/linux.service'
    displayName: Adding configuration for ${{ config.key }}

